-- MAKE THE INDEXES UNUSABLE DURING LOAD
-- THIS NO LONGER WORKS WITH PARTITIONED TABLES
-- CHANGE THIS FOR DEC
/*ALTER INDEX FACT_NO_LOB UNUSABLE;
ALTER INDEX IDX$$_11270001 UNUSABLE;
ALTER INDEX OBS_FACT_PT_IDX UNUSABLE;
ALTER INDEX OBSERVATION_FACT_PK UNUSABLE;
ALTER INDEX OBS_FACT_CONCEPT_IDX UNUSABLE;
ALTER INDEX FACT_CNPT_DATE_PT_IDX UNUSABLE;
ALTER INDEX OBS_FACT_CON_INST_PT_ENC UNUSABLE;
*/
INSERT /*+ APPEND */ INTO OBSERVATION_FACT 
SELECT
    /*+ PARALLEL 4 */
    ENCOUNTER_NUM,
    PATIENT_NUM,
    CONCEPT_CD,
    PROVIDER_ID,
    START_DATE,
    END_DATE,
    MODIFIER_CD,
    INSTANCE_NUM,
    VALTYPE_CD,
    LOCATION_CD,
    TVAL_CHAR,
    TO_CHAR(NVAL_NUM) AS NVAL_NUM,
    VALUEFLAG_CD,
    UNITS_CD,
    UPDATE_DATE,
    DOWNLOAD_DATE,
    IMPORT_DATE,
    SOURCESYSTEM_CD,
    UPLOAD_ID
FROM 
ACTS_ETL.OBSERVATION_FACT_STG;

COMMIT;
SELECT * FROM ACTS_ETL.OBSERVATION_FACT_STG;
SELECT * FROM ACTS_ETL.I2B2_PATIENT_MAPPING_STG;
SELECT * FROM OBSERVATION_FACT WHERE ENCOUNTER_NUM = 254716844;
SELECT * FROM PATIENT_MAPPING WHERE PATIENT_NUM = 6553311;
INSERT /*+ APPEND */ INTO PATIENT_MAPPING 
SELECT
    PATIENT_IDE,
    PATIENT_IDE_SOURCE,
    PATIENT_NUM,
    PATIENT_IDE_STATUS,
    PROJECT_ID,
    UPLOAD_DATE,
    UPDATE_DATE,
    DOWNLOAD_DATE,
    IMPORT_DATE,
    SOURCESYSTEM_CD,
    UPLOAD_ID
FROM ACTS_ETL.I2B2_PATIENT_MAPPING_STG;
COMMIT;

INSERT /*+ APPEND */ INTO PATIENT_DIMENSION 
SELECT
PATIENT_NUM,
    BIRTH_DATE,
    DEATH_DATE,
    RACE_CD,
    SEX_CD,
    VITAL_STATUS_CD,
    AGE_IN_YEARS_NUM,
    LANGUAGE_CD,
    MARITAL_STATUS_CD,
    RELIGION_CD,
    ZIP_CD,
    STATECITYZIP_PATH,
    INCOME_CD,
    PATIENT_BLOB,
    UPDATE_DATE,
    DOWNLOAD_DATE,
    IMPORT_DATE,
    SOURCESYSTEM_CD,
    UPLOAD_ID
FROM ACTS_ETL.I2B2_PATIENT_DIMENSION_STG;
SELECT * FROM I2B2_PATIENT_DIMENSION_STG;
COMMIT;
INSERT INTO ENCOUNTER_MAPPING 
SELECT
    ENCOUNTER_IDE,
    ENCOUNTER_IDE_SOURCE,
    PATIENT_IDE,
    PATIENT_IDE_SOURCE,
    ENCOUNTER_NUM,
    ENCOUNTER_IDE_STATUS,
    PROJECT_ID,
    UPLOAD_DATE,
    UPDATE_DATE,
    DOWNLOAD_DATE,
    IMPORT_DATE,
    SOURCESYSTEM_CD,
    UPLOAD_ID,
    ROWNUMBER
FROM ACTS_ETL.I2B2_ENCOUNTER_MAPPING_STG;
COMMIT;

INSERT /*+ APPEND */ INTO VISIT_DIMENSION 
SELECT
SOURCE_ID,
    ENCOUNTER_NUM,
    PATIENT_NUM,
    ACTIVE_STATUS_CD,
    START_DATE,
    END_DATE,
    INOUT_CD,
    LOCATION_CD,
    LOCATION_PATH,
    LENGTH_OF_STAY,
    UPDATE_DATE,
    DOWNLOAD_DATE,
    IMPORT_DATE,
    SOURCESYSTEM_CD,
    UPLOAD_ID
FROM ACTS_ETL.I2B2_VISIT_DIMENSION_STG;

COMMIT;
/*
ALTER INDEX FACT_NO_LOB REBUILD;
ALTER INDEX IDX$$_11270001 REBUILD;
ALTER INDEX OBS_FACT_PT_IDX REBUILD;
ALTER INDEX OBSERVATION_FACT_PK REBUILD;
ALTER INDEX OBS_FACT_CONCEPT_IDX REBUILD;
ALTER INDEX FACT_CNPT_DATE_PT_IDX REBUILD;
ALTER INDEX OBS_FACT_CON_INST_PT_ENC REBUILD;
*/
COMMIT;




